### ISSUE TITLE
AWAY

### ISSUE THREAD

**Issue by Mikaela** [kaniini/mammon#16]
I have auto-away when I detach tmux and I appear to be getting `AWAY: Unknown command` when I detach and attach.

Knowing when people are away and back can be helpful and this command not being supported can lead into awaynicks being used.

**Comment by ghost** [comment]
Pull requests accepted. I'd planned on integrating it into `METADATA`, however.

**Comment by kaniini** [comment]
AWAY is an RFC1459 command but as @Aerdan mentioned we plan to map it onto the metadata subsystem.

**Comment by kaniini** [comment]
So we will map this onto metakey `away`.  Now the question is, do we bother with `away-notify`?  Should `away-notify` be trumped by `metadata-notify`?

**Comment by Aerdan** [comment]
I'd say support both ways, but prefer the latter over the former; clients may support `away-notify`, but as `metadata-notify` is so new it still squeaks...

**Comment by Mikaela** [comment]
Many clients support `away-notify`, but `metadata-notify` is too new so most of clients don't currently support it. Of course if it's in core IRCv3.2 specification, clients will start supporting it.

**Comment by kaniini** [comment]
We decided that `away-notify` should trump `metadata-notify`, and that "smart" metadata should be namespaced inside the vendor namespace since clients can't use `/` in keys it all works nicely for our needs.

**Comment by DanielOaks** [comment]
I'll work on this.

**Comment by DanielOaks** [comment]
Closed with PR #29
