### ISSUE TITLE
basic IRCv3.2-draft compliance

### ISSUE THREAD

**Issue by kaniini** [kaniini/mammon#3]
See [ircv3 repo](/ircv3/ircv3-specifications) for specialized documentation.
- [x] capability negotiation 3.2
- [x] message-tags (provided by `ircreactor`)
- [x] MONITOR
- [x] metadata
  - [x] figure out how metadata interacts with properties.  are properties different?  if so, we need to submit a spec for 3.3.

**Comment by kaniini** [comment]
Some things, mammon-1.  Other things mammon-2.

**Comment by kaniini** [comment]
`intents` are being moved to experimental for ircv3.2.

**Comment by ghost** [comment]
Properties could be handled either in the `server.property` or `client.property` namespaces, depending on whether the specific property is user-editable or not.
