### ISSUE TITLE
ERR_NOSUCHCHANNEL instead of ERR_NOTONCHANNEL as a response to PART

### ISSUE THREAD

**Issue by progval** [kaniini/mammon#68]
Session log:

```
1450702410.733 1: connects to server.
1450702410.733 1 -> S: NICK foo
1450702410.733 1 -> S: USER username * * :Realname
1450702410.734 S -> 1: :MyLittleServer NOTICE foo :*** Looking up your hostname...
1450702410.735 S -> 1: :MyLittleServer NOTICE foo :*** Checking Ident
1450702410.736 S -> 1: :MyLittleServer NOTICE foo :*** Found your hostname: localhost
1450702410.736 S -> 1: :MyLittleServer NOTICE foo :*** No Ident response
1450702410.737 S -> 1: :MyLittleServer 001 foo :Welcome to the MyLittleNetwork IRC Network, foo!~username@localhost
[…]
1450702410.775 S -> 1: :MyLittleServer 376 foo :End of /MOTD command.
1450702410.775 1 -> S: PART #chan
1450702410.816 S -> 1: :MyLittleServer 403 foo #chan :No such channel
1450702410.856 1: disconnects from server.

```

Expected behavior:

```
:irc.example.com 442 foo #chan :You're not on that channel
```

RFCs 1459 and 2812 state:

> ```
>    403     ERR_NOSUCHCHANNEL
>                    "<channel name> :No such channel"
> 
>            - Used to indicate the given channel name is invalid.
> ```

(the name is misleading)

and:

> ```
>   442    ERR_NOTONCHANNEL
>          "<channel> :You're not on that channel"
> 
>     - Returned by the server whenever a client tries to
>       perform a channel affecting command for which the
>       client isn't a member.
> ```

**Comment by kaniini** [comment]
Either numeric is fine in my opinion.  It matches the behaviour of other IRCds, such as Charybdis and InspIRCd.

**Comment by progval** [comment]
Actually, InspIRCd sends ERR_NOSUCHNICK

**Comment by DanielOaks** [comment]
When the channel does not exist, we output `ERR_NOSUCHCHANNEL`. When the channel does exist and we're just not joined to it, we output `ERR_NOTONCHANNEL`. I think that's fairly sane and expected behaviour, and fits those two numerics.

**Comment by progval** [comment]
But the description of `ERR_NOSUCHCHANNEL` says it's only for invalid names

**Comment by DanielOaks** [comment]
AFAIK we reject that definition of `ERR_NOSUCHCHANNEL` and follow Charyb/Hybrid/some other ircds, using [`ERR_BADCHANNAME`](http://danieloaks.net/irc-defs/defs/ircnumerics.html#479) for that instead.

**Comment by progval** [comment]
I didn't know about this page, thanks
