### ISSUE TITLE
*raw shows our server pinging irc.znc.in?

### ISSUE THREAD

**Issue by pcolmer** [kaniini/mammon#95]
I'm trying to troubleshoot a problem where our Dockerised ZNC (the official container) doesn't appear to be connecting to Freenode and I'm trying to understand the output from *raw:

```
08:05 -!- Irssi: Starting query in Freenode with *raw
08:05 <*raw> YOU -> [MODE philip_colmer +i]
08:05 <*raw> YOU -> [PING irc.znc.in]
08:06 <*raw> YOU -> [PING irc.znc.in]
08:07 <*raw> YOU -> [PING irc.znc.in]
08:08 <*raw> IRC -> [:orwell.freenode.net NOTICE * :*** Looking up your hostname...]
08:08 <*raw> IRC -> [:orwell.freenode.net NOTICE * :*** Checking Ident]
08:08 <*raw> IRC -> [:orwell.freenode.net NOTICE * :*** Found your hostname]
08:08 <*raw> IRC -> [:orwell.freenode.net NOTICE * :*** No Ident response]
08:08 <*raw> IRC -> [:orwell.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl]
08:08 <*raw> IRC -> [:orwell.freenode.net CAP philip_colmer ACK :account-notify ]
08:08 <*raw> IRC -> [:orwell.freenode.net CAP philip_colmer ACK :extended-join ]
08:09 <*raw> IRC -> [:orwell.freenode.net CAP philip_colmer ACK :multi-prefix ]
08:09 <*raw> YOU -> [PING irc.znc.in]
08:09 <*raw> IRC -> [:orwell.freenode.net CAP philip_colmer ACK :sasl ]
08:09 <*raw> IRC -> [:orwell.freenode.net 451 * :You have not registered]
08:09 <*raw> IRC -> [AUTHENTICATE +]
08:09 <*raw> IRC -> [:orwell.freenode.net 904 philip_colmer :SASL authentication failed]
08:09 <*raw> IRC -> [AUTHENTICATE +]
08:09 <*raw> IRC -> [:orwell.freenode.net 900 philip_colmer philip_colmer!philip_col@linaro/philip-colmer philip_colmer :You are now logged in as philip_colmer.]
08:09 <*raw> IRC -> [:orwell.freenode.net 903 philip_colmer :SASL authentication successful]
08:09 <*raw> IRC -> [ERROR :Closing Link: gateway/shell/linaro/session (Too many user connections (global))]
```

Why is our server apparently pinging irc.znc.in? Or am I misunderstanding the output from *raw?

Thanks.

**Comment by DanielOaks** [comment]
Hey mate, unfortunately this server project hasn't been active for a fair while now, it'd be best to ask about this through ZNC's support channels over here: https://wiki.znc.in/FAQ#My_question_isn.27t_answered_here If you can't connect directly, connecting through freenode's webchat and asking should hopefully work.

My guess is that whatever side's pinging (the client or ZNC itself) is just grabbing the first server name it sees, ZNC sending a default one before it's fully connected to the freenode upstream. The good thing is that the parameter of `PING` (`irc.znc.in`) isn't actually used to direct messages and is just a value that the other side returns, so this shouldn't indicate any issue or worries about either side doing anything wrong. I'm not sure what's going on exactly but from the output you've got there there's something either on your end of freenode's end to resolve, so asking them directly would be best.

Best of luck sorting it out though!
